[package]
name = "rustorio-proptree"
version = "0.1.0"
authors = ["Janosch Gräf <janosch.graef@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
thiserror = "1.0"
serde = "1.0"
byteorder = "1.3"
pretty-hex = "0.2"

[dev-dependencies]
pretty_env_logger = "0.4"
