[workspace]
members = [
    "rustorio-circuits",
    "rustorio-core",
    "rustorio-data",
    "rustorio-data-derive",
    "rustorio-main",
    "rustorio-proptree",
    "rustorio-protoview",
    "rustorio-planner",
    "rustorio-remote/factorio-remote",
    "rustorio-remote/factorio-data",
]
