[package]
name = "rustorio-planner"
version = "0.1.0"
authors = ["Janosch Gräf <janosch.graef@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
dotenv = "0.15"
pretty_env_logger = "0.4"

rustorio-core = { path = "../rustorio-core" }
rustorio-data = { path = "../rustorio-data" }
